### ISSUE TITLE
about multidimensional array

### ISSUE THREAD

**Issue by ahmedsliman** [penoonan/laravel-iterable-validator#2]
Welcome, 

First thank you for this useful class.

I have an issue, my input fields named like user[1][phone], 1 mean one row of data related with user and phone is a field in this row, so how can i use the class in validate that phone is max length for example

Thanks

**Comment by penoonan** [comment]
Unless I'm misreading your question --- if your user input has a [1] at the end (and hopefully there's a preceding entry with a [0] at the end as well?), PHP is going to treat it like an array, so this should be basically just like in the README. I.e., you'd instantiate the validator:

    $input = ...;
    $normalRules = ...;

    $userRules = [
        'phone' => 'required|max_length_or_whatever',
    ];

    $validator = Validator::make($input, $rules);
    $validator->iterate('user', $userRules);

Does that help?
